//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_QueryTests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankedProduct
    {
        public Nullable<long> rownum { get; set; }
        public int categoryid { get; set; }
        public int productid { get; set; }
        public string productname { get; set; }
        public decimal unitprice { get; set; }
    }
}
